### ISSUE TITLE
stat_ld_annotation should have variable day/night length! 

### ISSUE THREAD

**Issue by qgeissmann** [rethomics/ggetho#17]
So far we hardcoded 1/2 -> L, 1/2 -> D

Thanks @hanhanhankim

**Comment by orijitghosh** [comment]
Any chance you could introduce a way to define different photoperiods?

**Comment by qgeissmann** [comment]
Hi, unless I misunderstood your question, this is already implemented. See `?ggetho::stat_ld_annotations`, the examples, and in particular, the arguments `period`,  `phase` and `l_duration`.  I hope it helps :)

**Comment by orijitghosh** [comment]
I missed `l_duration` previously. Thanks.
