### ISSUE TITLE
Choosing specifics gentoypes in a plot 

### ISSUE THREAD

**Issue by Georges-Farkouh** [rethomics/ggetho#28]
Hello, I am plotting sleep for three genotypes A,B and C using ggetho with the following code 

`ggetho(dt_curated, aes(y=asleep, colour=genotype)) +
  stat_pop_etho() +
  stat_ld_annotations()
`

This give me a sleep plot with all three genotypes. Is there a way to chose which genotypes to plot (ex. A and C)

**Comment by qgeissmann** [comment]
Hi @Georges-Farkouh ,
Sure, the simplest is to filter the data ahead:

For instance, to keep only genotype A, you can subset your table using:
```R
dt_curated[xmv(genotype) == "A"]
```

`xmv` is necessary as genotype is a "metavariable"

In your specic case, you can *match* genotype with the set {A, C} using the `%in%` operator:

```R
ggetho(dt_curated[xmv(genotype) %in% c("A", "C")], 
             aes(y=asleep, colour=genotype)) + 
                             stat_pop_etho() + 
                             stat_ld_annotations() 
```
Also see the [tutorial on behavr tables](https://rethomics.github.io/behavr.html)  in case it makes more sense.

I hope it helps!

**Comment by Georges-Farkouh** [comment]
Thank you @qgeissmann the second solution is exactly what i wanted as it is more practical for fast plots comparison between several genotypes
I am going to give the tutorial a look for details about the different operators that we can use
