### ISSUE TITLE
Time warp 24 hours, sleep curves don't go all the way until the end of day 

### ISSUE THREAD

**Issue by Georges-Farkouh** [rethomics/ggetho#29]
Hello, i am using time warp (24 hours) to average sleep behavior over multiple days in a single day (24 hours). However the sleep curve and the LD bar annotation do not reach the end of day, a period at the end of the day is missing as I see.  

`ggetho(dt_curated, aes(y=asleep, colour=genotype), time_wrap = hours(24)) +
      stat_pop_etho() +
      stat_ld_annotations() +
      facet_grid(genotype ~ .) +
      scale_y_continuous(name= "Fraction of time sleeping",labels = scales::percent)`

![Rplot](https://user-images.githubusercontent.com/52280036/70142404-72cbfd00-1699-11ea-8154-d132ebd79079.jpeg)

**Comment by qgeissmann** [comment]
Hi @Georges-Farkouh, 
As far as I remember, the missing period at the end of the day is intended. Indeed, the first point, at `00:00`, would be the same value as the last point, at `24:00`. It would be statistically dubious to have an artificially replicated measure. Does it make sense? Regarding the annotation range, you can extend it (or reduce it) with the argument `x_limits`. 

For instance:
```R
library(behavr)
library(ggetho)

metadata <- data.frame(id = sprintf("toy_experiment | %02d", 1:20),
				condition = c("A", "B"))
dt <- toy_activity_data(metadata, 3)
pl <-  ggetho(dt, aes(y = asleep),time_wrap=hours(24)) + 
			stat_pop_etho() + 
			stat_ld_annotations(x_limits=hours(c(0,24)))
```
![image](https://user-images.githubusercontent.com/1399684/70154563-8c535180-1665-11ea-9085-b7f71111a04d.png)

**Comment by Georges-Farkouh** [comment]
Yes it makes sense. Thank you for the clarification @qgeissmann
