### ISSUE TITLE
Bar plot functionality for ggetho

### ISSUE THREAD

**Issue by IllustratedMan-code** [rethomics/ggetho#39]
I would like a single value as an average activity over a time period for each individual. Somewhat like the graph I have attached but with Id's for each individual. I think this would be possible if I were able to melt the data like with library(reshape). Is there any way that I can do this with rethomics? The workflow would be: subset ->melt -> plot.
![averageplot](https://user-images.githubusercontent.com/60514384/90822093-eaae8600-e301-11ea-9781-016f6beaa518.jpg)

**Comment by qgeissmann** [comment]
In data.table, you can use `DT[,FUNCTION(ddd),by=KEY]`. this is very convenient to apply computation BY `id`. We have examples in the tutorial e.g.: https://rethomics.github.io/sleepr.html#summarise-data-per-animal
