### ISSUE TITLE
time_wrap when some individuals have NA values

### ISSUE THREAD

**Issue by brooksminer** [rethomics/ggetho#40]
I have a dataset of 12 individuals over 4 days. For one of the individuals, I had to remove the first ≈1 day of data - I replaced the activity values in this time range with NAs.

When I do a wrapped plot and facet by individual, the plot for the individual with the NA values is almost entirely empty. It seems that the mean function built into time_wrap will not handle NAs.

Is there a way to provide an argument to ggetho() so that the averaging performed by time_wrap will ignore NA values?

Thanks!

**Comment by qgeissmann** [comment]
Sure @brooksminer , there are two ways around. 1. use `na.omit()` on your data. 2. wrap the mean function.
Regarding 2.,  `ggetho()`  has a documented `summary_FUN` argument. The default value is mean, but you can replace it by an anonymous function as in `ggetho(...,...,..., summary_FUN = function(x) mean(na.omit(x)), ...`. Note that, you can use that to compute arbitrary functions or built-in ones such as `sum()`, `median()`, ... I hope it helps :). let me know. Closing for now.

**Comment by brooksminer** [comment]
Thanks Quentin! I was trying to figured out where to put the na.omit() wrapper - didn't think to but it around the data itself, haha. Thanks for answering my simple question so quickly.

**Comment by qgeissmann** [comment]
no problem. don't hesitate to ask more at any time. Enjoy the analysis :)
