### ISSUE TITLE
plotting raw data behind a ggetho figure - specifically stat_pop_etho

### ISSUE THREAD

**Issue by masterofmolerats** [rethomics/ggetho#50]
Hi, thanks for making this very helpful suit of tools! I'm analyzing activity patterns of rodents and plotting proportion of activity over a 24 hour period. I first did it using quite a few summarizes, then realized your packages can do the same for me. But I'm having trouble adding the raw data behind the line created with population plot. My raw data is every 2 seconds. I tried adding summary_time_window = seconds(2) inside stat_pop_etho but it didn't work. Is there a way to do this easily? or do I need to perform my own summary of the proportions per second over a 24hr period, convert to time to seconds, and then plot?

code example using fly dataset:
```
URL <- "https://github.com/rethomics/rethomics.github.io/raw/source/material/sleep_dam.RData"
load(url(URL))

ggetho(dt, aes(y=asleep), time_wrap = hours(24)) +
  stat_pop_etho(summary_time_window = seconds(2)) + 
  stat_pop_etho() +
  stat_ld_annotations(phase = hours(5.8), l_duration = hours(12.9)) +
  scale_y_continuous("Proportion of Time Active", limits = c(0,1))

```
I wanted a figure similar to this one
![example](https://github.com/rethomics/ggetho/assets/94361957/4fb10591-819c-4d31-88f6-1790e37c9c3e)

**Comment by qgeissmann** [comment]
Hi, thanks for your question.
It is somewhat hard to understand/help without seeing the raw data or the code you tried for it. My understanding, is that you are struggling to convert your data into a "behave table"?

**Comment by masterofmolerats** [comment]
Hi, I have my data in a behave table just fine. I was wanting to put my 2s data as a bar plot behind the activity curve. But it's a moot point since my supervisor said it's not necessary to plot the raw data.
