### ISSUE TITLE
error when trying to wrap data along a circadian day

### ISSUE THREAD

**Issue by ghost** [rethomics/ggetho#7]
Hello,
Thanks for making the ggetho package. I am having some trouble wrapping my DAM2 data along a circadian day.
![screen shot 2017-10-17 at 3 00 20 pm](https://user-images.githubusercontent.com/26473149/31683810-ec1f1baa-b34b-11e7-90b7-26fb6b174ce4.png)
I do not, however, get this problem when I set y=asleep or y=moving with the toy data. Is there a way within the rethomics framework to turn my 'activity' data into something like 'moving' or 'asleep'?
Thanks

**Comment by qgeissmann** [comment]
hey, great to have some user feedback.
I will look that up tomorrow.
Can you try `dt[, t := as.numeric(t)]`, and then rerun your line?
cheers,

**Comment by ghost** [comment]
Hi, thanks, that seems to be a quick fix. I no longer get an error. However, the x axis doesn't look quite right:
![image](https://user-images.githubusercontent.com/26473149/31685976-ed0d1fba-b352-11e7-9439-571c5b69dac5.png)
In any case, I look forward to your response tomorrow! 
thanks,

**Comment by qgeissmann** [comment]
ok, did you just load some standard data using `damr`?
Can you show activity, unwrapped correctly?

**Comment by ghost** [comment]
Hi, yes, my data is regular dam data that I linked and loaded using damr. 
I can correctly show unwrapped activity, I think? When I write:
![screen shot 2017-10-17 at 4 08 05 pm](https://user-images.githubusercontent.com/26473149/31686830-6a347cd4-b355-11e7-8621-15888fd28fdd.png)
I get:
![image](https://user-images.githubusercontent.com/26473149/31686839-7198041e-b355-11e7-9249-4a0f1d2d5b44.png)

**Comment by qgeissmann** [comment]
can you try to plot population averages in both cases? :

`ggetho(.....) + stat_pop_etho()`

**Comment by ghost** [comment]
![screen shot 2017-10-17 at 4 12 42 pm](https://user-images.githubusercontent.com/26473149/31687413-20f8140c-b357-11e7-8aeb-cc441f2c54b5.png)

![screen shot 2017-10-17 at 4 22 17 pm](https://user-images.githubusercontent.com/26473149/31687499-66fd2c1c-b357-11e7-97c3-fc2a30fbbd2c.png)

**Comment by qgeissmann** [comment]
can you print your data?
`print(dt)`
do you have less that 30min of data?

**Comment by ghost** [comment]
here is the data:
![screen shot 2017-10-17 at 5 48 39 pm](https://user-images.githubusercontent.com/26473149/31691263-78bd9548-b363-11e7-9b6b-00942a9dd606.png)

I have more than 30 mins of data--at least a few days' worth--for all animals.

**Comment by qgeissmann** [comment]
Hey, I am trying to reproduce/ understand the issue.
Are you sure you have more than 30min? 
For instance, the last animal seems to have only 300s

`dt[, .N ,by="id"]`

Can we see just a tile plot
`ggetho(dt, aes(z=activity)) + stat_tile_etho()`

**Comment by ghost** [comment]
You're right ... something seems wrong. Here is the tile plot:
![image](https://user-images.githubusercontent.com/26473149/31718008-3b9e332e-b3dc-11e7-87c4-6686b4384ad1.png)
Weird, I should definitely have more than 300 s of data for each animal :(

**Comment by qgeissmann** [comment]
It seems to be a problem in data loading then. If you send your code to load the data, and your metadata file, I may be able to help...

**Comment by ghost** [comment]
Sure, that's not a problem. Can I send you those files via e-mail?

**Comment by qgeissmann** [comment]
sure, send them at `qgeissmann <at> gmail <dot> com` ;)

**Comment by ghost** [comment]
great! just sent :)
thanks!

**Comment by qgeissmann** [comment]
I think this is mainly solved now. @hanhanhankim  Are we ok closing this?

**Comment by ghost** [comment]
Yes! :)
